### ISSUE TITLE
can not run,Provision failed with message: The device used is not whitelisted for Instant Apps deployment.. Do you want to retry

### ISSUE THREAD

**Issue by frankfancode** [googlesamples/android-instant-apps#1]
when I run hello-split use android studio 3 canary 1, it show a dialog window
> "Provision failed with message: The device used is not whitelisted for Instant Apps deployment.. Do you want to retry?"

my device is nexus 5,  android version is 6.0.1 , setting -> google -> instant app has open.

Look forward to your reply. thank you

**Comment by keyboardsurfer** [comment]
We currently don't support the Nexus 5 as a device for Android Instant Apps. An emulator with Google Play Services and a logged in user will allow you to develop as well. Also, there's a comprehensive list of compatible devices [in the documentation](https://developer.android.com/topic/instant-apps/getting-started/setup.html#setup-emulator).
