### ISSUE TITLE
Unable to connect to Google Play Service.

### ISSUE THREAD

**Issue by df13954** [googlesamples/android-instant-apps#11]
```
Unable to connect to Google Play Service. ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}  token=59b25c9c-8c78-4340-8292-f920d9a4273f

06/05 17:11:54: Launching instantapp
Uploading Instant App to pre O device.
Starting / refreshing Instant App services
DevMan error: Unable to connect to Google Play Service. ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}  
$ adb shell pm uninstall com.dolphinwifi.myapplication
Unknown failure (at android.os.Binder.execTransact(Binder.java:565))
Error while Uploading and registering Instant App

```

nexus 5x Android 7.1.2
gps 11.0.38
gps for instant apps 1.9
instant apps dev manager 1.0.155672963

**Comment by adamkoch** [comment]
Can you try the emulator? See:
https://stackoverflow.com/a/44052798/268156

**Comment by df13954** [comment]
I'm not using the simulator. Buzzfeed.com/stasty this connection can be turned on properly.
Currently in China, the 5x version of nexus is used in Hongkong。The computer can't run the simulator at the moment。。

**Comment by adamkoch** [comment]
To workaround the error "Unable to connect to Google Play Service" you will need to use the emulator as per the stackoverflow post.

**Comment by df13954** [comment]
I upgraded the system to Android 8.0, so that it can start properly. I don't want to use the simulator
