### ISSUE TITLE
Running the app fails on Android Studio 3.0 Canary 4

### ISSUE THREAD

**Issue by zmdominguez** [googlesamples/android-instant-apps#14]
Android Studio 3.0 Canary 4
Build #AI-171.4101728, built on June 15, 2017
JRE: 1.8.0_112-release-b736 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.10.5

Tried running `multi-feature-module` via Android Studio and it complains of having no default activity set. Editing the run configuration to include the `default-url` (`https://multi-feature.instantappsample.com/main`) brings up an interesting error:
![screen shot 2017-06-21 at 12 44 28](https://user-images.githubusercontent.com/410969/27365578-22e36ba2-5684-11e7-9b7e-ed743557512a.png)

![screen shot 2017-06-21 at 12 40 36](https://user-images.githubusercontent.com/410969/27365575-1c263cfe-5684-11e7-8d4e-58a02c3111e8.png)

Merging the intent filters in the manifest seem to fix the issue:
```
<data android:host="multi-feature.instantappsample.com"
                      android:pathPrefix="/main"
                      android:scheme="https" />
<data android:host="multi-feature.instantappsample.com"
                      android:pathPrefix="/main"
                      android:scheme="http" />
```

FWIW, I remember being able to run this sample on Canary 3.

**Comment by keyboardsurfer** [comment]
We are aware of some pain points with the latest Canary version.
Please use another version from the [Android Studio release archive](https://developer.android.com/studio/archive.html).

**Comment by keyboardsurfer** [comment]
Please try Canary-5 and re-open if the issue still occurs.
