### ISSUE TITLE
InstantApp: Foreground service ?

### ISSUE THREAD

**Issue by Karthi-R** [googlesamples/android-instant-apps#15]
Unable to use **foreground service** inside InstantApp feature module. Getting below runtime security exception.

`java.lang.RuntimeException: Unable to start activity ComponentInfo{..XYZActivity}: java.lang.SecurityException: Method class android.app.ActivityManagerProxy.getServices not available to instant apps`

https://stackoverflow.com/questions/44656049/android-instantapp-foreground-service

Please suggest the right way to do this.

**Comment by keyboardsurfer** [comment]
Thanks for posting this question here as well.
The answer on StackOverflow is correct.
You'll have to wait until the issue is resolved
and a new version of Instant Apps is available on your device.

**Comment by Karthi-R** [comment]
@keyboardsurfer Is this resolved ?
