### ISSUE TITLE
won't build -> Error:Unable to find method 'com.android.build.gradle.tasks.factory.AndroidUnitTest.setTestClassesDirs(Lorg/gradle/api/file/FileCollection;)V'.

### ISSUE THREAD

**Issue by holoduke** [googlesamples/android-instant-apps#16]
I am trying to build multi-feature-module on android studio 3 canary 4
I had to change the build gradle, because it was not able to find gradle:3.0.0-alpha1
But i am getting an error when i press gradle sync button. I cleared cache, deleted and recloned the project. I won't work. Also the error does not make sense at all. 

Error:Unable to find method 'com.android.build.gradle.tasks.factory.AndroidUnitTest.setTestClassesDirs(Lorg/gradle/api/file/FileCollection;)V'. 

    `ext {
    buildTools = "26.0.0"
    compileSdk = 25
    targetSdk = 25
    minSdk = 23
    versionCode = 1
    versionName = "1.0"
    supportLib = "25.3.1"
    glide = "3.7.0"
    retrofit = "1.9.0"
    keystoreProperties = new Properties()
}

def keystorePropertiesFile = rootProject.file("keystore.properties")
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha4'
    }
}
allprojects {
    repositories {
        maven {
            url 'https://maven.google.com'
        }
    }
}`

**Comment by keyboardsurfer** [comment]
Canary 4 was known to introduce some bugs for Instant Apps development.
Please see whether Canary 5 fixes the problems you've been experiencing.

**Comment by keyboardsurfer** [comment]
Canary 6 is available now and the samples have been updated. Please check if the issue persists. I'm happy to re-open and investigate if that is the case.
