### ISSUE TITLE
Flavors example not working on 3.0 Canary 5

### ISSUE THREAD

**Issue by LuigiPapino** [googlesamples/android-instant-apps#17]
If I import the `flavors` project in Android Studio 3.0 Canary 5, I see this in the Build Variants panel:
![selection_023](https://user-images.githubusercontent.com/402236/27773233-32f338b4-5f6d-11e7-9cf7-c37fd4d23e38.png)

Trying to change for example the base module to  `freeDebug`  the selection is back to `paidDebug` and I see this warning:
![selection_024](https://user-images.githubusercontent.com/402236/27773252-9679b318-5f6d-11e7-92fb-cbf83cd19728.png)
```
Warning:Module 'base' has variant 'freeRelease' selected, but the modules ['bye', 'hello'] depend on variant 'paidDebug'
<a href="select.conflict.in.variants.window">Select 'base' in "Build Variants" window</a><br><a href="fix.conflict">Fix problem</a>
```

I do see in the list of Build Variants for the feature modules this extra varaints:
- freeDebugFeature
- freeReleaseFeature
- paidDebugFeature
- paidReleaseFeature

Is this expected? I can't figure out how to switch build variants and why they aren't aligned to the app module.

**Comment by keyboardsurfer** [comment]
This is a known issue.
As a workaround, make sure that your feature module flavors match the actual package flavors.
So having all set to "freeDebug" or "paidDebug" fixes the problem you're experiencing.

**Comment by keyboardsurfer** [comment]
The sample works well with Canary9. An update to the build files is incoming soon.
