### ISSUE TITLE
Side loading instant app failed: Reading bundle timed out

### ISSUE THREAD

**Issue by Karthi-R** [googlesamples/android-instant-apps#19]
After updating Android Studio 3.0 **(Canary-4 > Canary-5)** & Emulator system image from revision **(20 > 21)**. I'm unable to run the instant App through emulator. Always I'm getting the error message saying 

> "Side loading instant app failed: Reading bundle timed out."

Posted my issue in SO [here](https://stackoverflow.com/questions/44908139/side-loading-instant-app-failed-reading-bundle-timed-out); but no solution yet.

**Comment by Karthi-R** [comment]
Now I'm unable to continue my **InstantApp** work. Requesting some reply on this issue.

**Comment by Karthi-R** [comment]
Found a workaround in Android studio release notes [here](https://androidstudio.googleblog.com/2017/06/android-studio-30-canary-5-is-now.html). This is a known-issue under Android Studio canary-5

**Comment by keyboardsurfer** [comment]
Please try again with Canary-6 and the updated samples.

**Comment by keyboardsurfer** [comment]
We're now at beta1. If this issue still persists, please re-open.

**Comment by prakashbalab24** [comment]
I am still getting this error. I tried to clear cache also.

**Comment by shivamsriva31093** [comment]
Yesterday I was able to run the instant app on Moto G5 plus Android 7.0 but today the app builds but is unable to install saying the same error. I am using Android studio 3.0 stable channel release with build tools version 26.

**Comment by prakashbalab24** [comment]
Hello @shivamsriva31093 , I had the same problem in same device, go to your settings -> apps -> "Instant Apps Development Manager" and try to uninstall for all users and run again.. it worked in my case. Just try it out.
