### ISSUE TITLE
Side loading instant app failed:Failure when trying to read bundle.

### ISSUE THREAD

**Issue by donly** [googlesamples/android-instant-apps#21]
Full error logs here,

> Side loading instant app failed: Failure when trying to read bundle. Instant App com.example.instantdemo requires an SDK version which is newer than the one installed on device.  Please update the SDK on the device. 

The development environment same as https://developer.android.com/topic/instant-apps/getting-started/setup.html

> Android Studio 3.0 Canary 7
> Build #AI-171.4182969, built on July 15, 2017
> JRE: 1.8.0_152-release-884-b01 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.5
> 

> compileSdkVersion 26
> buildToolsVersion "26.0.0"
> minSdkVersion 23
> targetSdkVersion 26

Google Play services for Instant Apps version is `version 1.9-sdk-155682639`.

How to solve this issue?

**Comment by donly** [comment]
When using Android O x86 emulator, it works.

**Comment by zlern2k** [comment]
Thanks so much for posting the workaround; this was driving me bonkers.
