### ISSUE TITLE
Lifecycle Fragments

### ISSUE THREAD

**Issue by nicholaspark09** [googlesamples/android-instant-apps#25]
It doesn't seem that the `LifecycleFragment` actually works in feature modules. I don't think I'm the only one with the issue or if this is the right channel to be posting on. :/

**Comment by keyboardsurfer** [comment]
Maybe this [issue over on the Google Issuetracker](http://issuetracker.google.com/64233187) can help you.

**Comment by nicholaspark09** [comment]
I think it should at least be mentioned somewhere in the documentation as our company is looking to use instant apps in tandem with `viewmodel`s

**Comment by keyboardsurfer** [comment]
It is documented in the [new configurations](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations) section of the gradle plugin.


> api:
The dependency is available to the module at compile time, and it's **also available to the consumer of the module at compile time and runtime**. This configuration behaves just like compile (which is now deprecated), and you should **typically use this only in library modules**. App modules should use implementation, unless you want to expose its API to a separate test module.
