### ISSUE TITLE
Non-upgradable to installed app

### ISSUE THREAD

**Issue by banaszeknorbert** [googlesamples/android-instant-apps#27]
Hello, 
I know that this error is not related to this repository, but I'm confused with some situation.
A few days ago I wrote a post on stackoverflow but I didn't receive an answer. [Link](https://stackoverflow.com/questions/45975231/google-play-console-error-non-upgradable-to-installed-app)
I'm trying to upload my instant app apks, but when Itry to rollout, I see this: 

**Non-upgradable to installed app**
**PROBLEM**
Some users of this Instant App APKs will not be eligible for any of the APKs in your installed app.
**RESOLUTION**
Ensure that the targeting of your Instant App APKs matches the targeting of your APKs.

My project structure is:
![zrzut ekranu 2017-09-04 o 17 16 42](https://user-images.githubusercontent.com/10154105/30032235-f8af6ae2-9194-11e7-9f27-90a2b0db77e6.png)
Where:
- blogspace-base is base feature with: 
```
    application project(':blogspace-apk')
    feature project(':blogspace-item-details')
    api project(':shared')
    api project(':rxfirebase')
```
- blogspace-ui is feature with:
```
    api project(':blogspace-base')
    implementation project(':shared')
    implementation project(':customcomponents')
    implementation project(':materialsearchbar')
    implementation project(':admobadapter')
    implementation project(':base64thumbs')
    implementation project(':blogspace-chrome')
    implementation project(':rxfirebase')
```
- blogspace-item-details is feature module with:
```
    api project(':blogspace-base')
    implementation 'com.google.android.instantapps:instantapps:1.0.0'
```
- blogspace-apk is apk module with:
```
    implementation project(':blogspace-ui')
    implementation project(':blogspace-item-details')
```
- blogspace-instant is instant app module with:
```
    implementation project(':blogspace-base')
    implementation project(':blogspace-item-details')
```
Others module's are libraries. (Note that module blogspace-ui is not included in instant app).
All modules has: minSdkVersion 18, targetSdkVersion 26, compileSdkVersion 26.
Correct me if I'm wrong, but instant apps targeting matches one to one targeting of installable app. So, all users of instant app should be able to download and install installable app.

Is the error which I see is due to configuration / code errors? Or because of errors in the Google Play console?

Please help.

**Comment by ibrahimkarahan** [comment]
Do you have differences between uses-feature declarations or ABI support between the instant and the installable app?

**Comment by iamBedant** [comment]
@banaszeknorbert please check version code for your app and instant apps whether they are same or not.

**Comment by keyboardsurfer** [comment]
Marked as solved on StackOverflow.

**Comment by Madhuri98** [comment]
i got same error while uploading instant app. 
i try for many different different version code but not solve the error.
any solution?
![Capture](https://user-images.githubusercontent.com/17897595/56268340-b83db900-610e-11e9-9740-4036c5ae5616.PNG)
