### ISSUE TITLE
google-services plugin did nothing for installed app

### ISSUE THREAD

**Issue by chievent** [googlesamples/android-instant-apps#29]
I ran the analytics demo with the "installed" configuration. but it did not even try to generate the gms related values, "gcm_defaultSenderId" for example.

**Comment by keyboardsurfer** [comment]
Did you follow the [Getting Started](https://github.com/googlesamples/android-instant-apps/tree/master/analytics#getting-started) section of the repository readme?

**Comment by keyboardsurfer** [comment]
Closing this issue as stale. Feel free to re-open and follow up.
