### ISSUE TITLE
InstantApp: package not for download 26.0.0-rc2

### ISSUE THREAD

**Issue by balrampandey19** [googlesamples/android-instant-apps#3]
![screenshot from 2017-05-19 13-00-51](https://cloud.githubusercontent.com/assets/7222064/26237607/7c55a66a-3c93-11e7-946a-bc39b0fdefa1.png)

**Comment by keyboardsurfer** [comment]
You'll have to get the build tools from the canary channel.
From the CLI run `sdkmanager "build-tools;26.0.0-rc2" --channel=3`.

**Comment by darkpiv** [comment]
you need to use 3.0 canary for this one I guess.

**Comment by balrampandey19** [comment]
thanks, @darkpiv  @keyboardsurfer it's working on **android studio 3.0.**
