### ISSUE TITLE
How to sharing data between two app using intent and get result with onActivityResult ?

### ISSUE THREAD

**Issue by DILEEP-YADAV** [googlesamples/android-instant-apps#30]
Hi! Please help me! How to sharing data between two app using intent and get result with onActivityResult ?

**Comment by keyboardsurfer** [comment]
Taken from the [Android Instant Apps FAQ](https://developer.android.com/topic/instant-apps/faqs.html): 

> Instant apps can launch an installed app by firing an implicit intent, but they cannot launch most installed apps using an explicit intent. Installed apps can make themselves available to interact with instant through explicit intents.

**Comment by DILEEP-YADAV** [comment]
Thanks, bro! I resolved myself, with Action firing with Intent to another app! Basically, I am developing banking app background lib for communicating securely with the server with lots of algorithms. Instant apps are differed think.
Once again thank to join me.
