### ISSUE TITLE
Failed to load instant app in release build

### ISSUE THREAD

**Issue by FantasyCheese** [googlesamples/android-instant-apps#32]
Everything works fine in debug build, but when I switch to release build, error messages look like this:

```
10/19 14:02:10: Launching instant
Side loading instant app.
Side loading instant app.
Side loading instant app.
Side loading instant app.
Side loading instant app failed: Failure when trying to read bundle. Failed to parse app: /data/local/tmp/aia/instant-release.zip 
Error while Uploading and registering Instant App
```
I have tried these combinations:
modules: hello-feature-module, hello-java, hello-kotlin, and my own project
actions: rebuild, clear cache, clear data and uninstall "Instant Apps Dev Manager"
environment:  Android Studio 3.0.0 RC1, 3.0.0 beta7

Thank you for your help!

**Comment by keyboardsurfer** [comment]
I'm seeing this issue only on projects that are not signed.
The samples do not have a valid release signing configuration, which is intentional.
Does the issue persist with a release version which contains signed apks, such as the one generated via Android Studio?

**Comment by akhileshAwasthi** [comment]
I have the same issue running my instant app on emulator. It is there even when i try to run a release version which has signed APKs. My app used to run flawlessly in debug mode on emulator.

**Comment by jamie1052741705** [comment]
I have the same issue!

**Comment by WOLVIE97** [comment]
Damn...

**Comment by keyboardsurfer** [comment]
Android Studio and the build tools have moved on a bit since December. No more reports of the issue. Closing it as stale. If it re-occurs, please open again.
