### ISSUE TITLE
multi-feature-module uses api instead of implementation

### ISSUE THREAD

**Issue by mustafaberkaymutlu** [googlesamples/android-instant-apps#35]
The [Android documentation](https://developer.android.com/topic/instant-apps/getting-started/structure.html#structure_of_an_instant_app_with_multiple_features) says feature modules should use "implementation" instead of "api" while adding base module in their dependencies.

"The two individual feature modules use the implementation project expression within their dependencies block"

All samples that have base modules use "implementation" but multi-feature-module sample uses "api" in [here](https://github.com/googlesamples/android-instant-apps/blob/master/multi-feature-module/detail/build.gradle#L54) and [here](https://github.com/googlesamples/android-instant-apps/blob/master/multi-feature-module/main/build.gradle#L54).

**Comment by keyboardsurfer** [comment]
Thanks for reporting this issue. It'll be fixed with the next sample release.

**Comment by keyboardsurfer** [comment]
Shipped with today's release.
