### ISSUE TITLE
Session 'instant': Error Launching URL

### ISSUE THREAD

**Issue by SwayChen** [googlesamples/android-instant-apps#38]
Hope get response as soon as possible, thanks a lot! >_<

I didn't change any thing of the sample project.

The picture following is the instant APP run configuration.

![image](https://user-images.githubusercontent.com/6345749/33316749-0a570b42-d470-11e7-9398-26267e823507.png)

**Comment by keyboardsurfer** [comment]
I can't reproduce this issue. The URL works fine on my machine with multiple API versions on Android Studio 3.0.0.
Which version are you using? Are there any changes that you made?

**Comment by SwayChen** [comment]
**`Android Studio 3.0.1`**. The following picture is what change I made: 
![image](https://user-images.githubusercontent.com/6345749/33352990-851ba074-d4e6-11e7-8562-5467e1455971.png)

What's more, when I try test the app links, it works but not instant.
![image](https://user-images.githubusercontent.com/6345749/33353083-f40cc71a-d4e6-11e7-9f9d-f910a63ff3a9.png)

**Comment by SwayChen** [comment]
Thanks for your reply! 

Android Studio 3.0.1. I just try it again & found it works fine. Oh my god, it shows errors all yesterday!

I meet troubles in change my project to Instant App. Would you mind give me a instant messaging method to contact you? you can send it to my email: ████████████ & I will keep secret. :)

**Comment by keyboardsurfer** [comment]
I'm happy this works again for you.
Generally I recommend asking questions not related directly to the samples on [StackOverflow](https://stackoverflow.com/questions/tagged/android-instant-apps) so more people can search and find an answer to your questions.
