### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by LoveMyBaby** [googlesamples/android-instant-apps#39]
Hey, it's ok, I publish develop instant app on play store.  error messages:
You must use at least one APK that maps to the "xxxx.com" site via the network "intent-filter" when I publish to preview instant app.
what's problem?

**Comment by keyboardsurfer** [comment]
This is not a question related to the samples. Please use [StackOverflow](https://stackoverflow.com/questions/tagged/android-instant-apps).
Also, see the developer documentation on [this particular issue](https://developer.android.com/topic/instant-apps/getting-started/prepare.html#default-url).
