### ISSUE TITLE
Reading bundle timed out

### ISSUE THREAD

**Issue by iRuoBin** [googlesamples/android-instant-apps#42]
IDE: Android Studio 3.0.1  Device: Samsung C5 Pro  (Google Account Signin, InstantApp turn On)
Log: 01/25 16:43:00: Launching instant
Side loading instant app.
Side loading instant app.
Side loading instant app.
Side loading instant app.
Side loading instant app failed: Reading bundle timed out.
Error while Uploading and registering Instant App

**Comment by keyboardsurfer** [comment]
Duplicate of #32
