### ISSUE TITLE
"Missing google_app_id. Firebase Analytics disabled." when running installed app of Analytics sample.

### ISSUE THREAD

**Issue by scm573** [googlesamples/android-instant-apps#44]
Hi,

I'm facing the problem as I wrote in the title, with the latest version of Firebase.
The instant app works fine and I can find myself immediately being tracked on StreamView. However when running the installed one, the error came out and of course nothing appears on StreamView.

> 03-26 10:00:29.308 13498-13514/com.example.android.instant.analytics E/FA: GoogleService failed to initialize, status: 10, Missing google app id value from from string resources with name google_app_id.
03-26 10:00:29.318 13498-13514/com.example.android.instant.analytics E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
03-26 10:00:29.324 13498-13514/com.example.android.instant.analytics E/FA: Uploading is not possible. App measurement disabled

Anyone has ideas?

**Comment by scm573** [comment]
The root cause seems to be that Firebase hasn't supported Instant Apps yet. So for now, a workaround is to manually add the google_app_id into the feature module as a string resource.

Thanks for the support from Firebase team.

**Comment by fmmarzoa** [comment]
@scm573 could you be more specific? you mean in the manifest? In the build.gradle file of the instant app?

TIA
