### ISSUE TITLE
"Try now" button not showing up with hello-java example

### ISSUE THREAD

**Issue by frafork** [googlesamples/android-instant-apps#46]
Hi, I'm using hello-java example.
I updated Android Manifest with the correct URLs and uploaded both installed and instant app to Google Play Console but the "Try now" button is not showing up in Google Play Store.

If I use adb to trigger the intent on a real device, the device loads the instant app correctly.

adb shell am start -a android.intent.action.VIEW -d "https://xxx/hello"

Any idea?

Thank you

**Comment by keyboardsurfer** [comment]
Does that issue only occur with the sample in question?
The setup looks okay and should be eligible for the "Try now" feature [as per documentation](https://developer.android.com/topic/google-play-instant/getting-started/convert-to-instant-app#enable-try-now).

**Comment by miguelmontemayor** [comment]
Closing this issue as stale. Feel free to re-open and follow up.
