### ISSUE TITLE
Android Architecture Components ( Android Jetpack ) breaks Instant Apps

### ISSUE THREAD

**Issue by ekhaled667** [googlesamples/android-instant-apps#47]
I have an android project that supports instant apps.
So, I have these in the `base feature`

    api 'androidx.appcompat:appcompat:1.0.0-alpha1'
    api 'androidx.constraintlayout:constraintlayout:1.1.0'
    api "androidx.lifecycle:lifecycle-extensions:2.0.0-alpha1"

when I have these the `installable app` doesn't launch with the following error `Default activity not found`

When I remove `api "androidx.lifecycle:lifecycle-extensions:2.0.0-alpha1"`
the `installable app` doesn't give errors, but of course I'm missing a direct dependency here, so it doesn't build.

I have tried every version of the support library alongside every version and module of the new architecture components, I even tried using `implementation` instead of `api`, but nothing works.

It appears as if the architecture components break instant apps.

Also there are no conflicts.

`
+--- androidx.appcompat:appcompat:1.0.0-alpha1
|    +--- androidx.annotation:annotation:1.0.0-alpha1
|    +--- androidx.core:core:1.0.0-alpha1
|    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    +--- androidx.collection:collection:1.0.0-alpha1
|    |    |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0-alpha1
|    |         +--- androidx.lifecycle:lifecycle-common:2.0.0-alpha1
|    |         |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    |         +--- androidx.arch.core:core-common:2.0.0-alpha1
|    |         |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    |         \--- androidx.annotation:annotation:1.0.0-alpha1
|    +--- androidx.collection:collection:1.0.0-alpha1 (*)
|    +--- androidx.cursoradapter:cursoradapter:1.0.0-alpha1
|    |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    +--- androidx.legacy:legacy-support-core-utils:1.0.0-alpha1
|    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    +--- androidx.documentfile:documentfile:1.0.0-alpha1
|    |    |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    |    +--- androidx.loader:loader:1.0.0-alpha1
|    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    +--- androidx.lifecycle:lifecycle-livedata-core:2.0.0-alpha1
|    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0-alpha1 (*)
|    |    |    |    +--- androidx.arch.core:core-common:2.0.0-alpha1 (*)
|    |    |    |    \--- androidx.arch.core:core-runtime:2.0.0-alpha1
|    |    |    |         +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |         \--- androidx.arch.core:core-common:2.0.0-alpha1 (*)
|    |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0-alpha1
|    |    |         \--- androidx.annotation:annotation:1.0.0-alpha1
|    |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0-alpha1
|    |    |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    |    \--- androidx.print:print:1.0.0-alpha1
|    |         \--- androidx.annotation:annotation:1.0.0-alpha1
|    +--- androidx.fragment:fragment:1.0.0-alpha1
|    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0-alpha1
|    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0-alpha1 (*)
|    |    |    +--- androidx.customview:customview:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    \--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    +--- androidx.viewpager:viewpager:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0-alpha1 (*)
|    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0-alpha1 (*)
|    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0-alpha1 (*)
|    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0-alpha1 (*)
|    |    |    +--- androidx.interpolator:interpolator:1.0.0-alpha1
|    |    |    |    \--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    +--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    |    \--- androidx.interpolator:interpolator:1.0.0-alpha1 (*)
|    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0-alpha1
|    |    |    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    |    |    \--- androidx.core:core:1.0.0-alpha1 (*)
|    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0-alpha1 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0-alpha1 (*)
|    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    +--- androidx.loader:loader:1.0.0-alpha1 (*)
|    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0-alpha1 (*)
|    +--- androidx.vectordrawable:vectordrawable:1.0.0-alpha1
|    |    +--- androidx.annotation:annotation:1.0.0-alpha1
|    |    \--- androidx.core:core:1.0.0-alpha1 (*)
|    \--- androidx.vectordrawable:vectordrawable-animated:1.0.0-alpha1
|         +--- androidx.vectordrawable:vectordrawable:1.0.0-alpha1 (*)
|         \--- androidx.legacy:legacy-support-core-ui:1.0.0-alpha1 (*)
+--- androidx.constraintlayout:constraintlayout:1.1.0
|    \--- androidx.constraintlayout:constraintlayout-solver:1.1.0
\--- androidx.lifecycle:lifecycle-extensions:2.0.0-alpha1
     +--- androidx.lifecycle:lifecycle-runtime:2.0.0-alpha1 (*)
     +--- androidx.arch.core:core-common:2.0.0-alpha1 (*)
     +--- androidx.arch.core:core-runtime:2.0.0-alpha1 (*)
     +--- androidx.fragment:fragment:1.0.0-alpha1 (*)
     +--- androidx.lifecycle:lifecycle-common:2.0.0-alpha1 (*)
     +--- androidx.lifecycle:lifecycle-livedata:2.0.0-alpha1
     |    +--- androidx.arch.core:core-runtime:2.0.0-alpha1 (*)
     |    +--- androidx.lifecycle:lifecycle-livedata-core:2.0.0-alpha1 (*)
     |    \--- androidx.arch.core:core-common:2.0.0-alpha1 (*)
     +--- androidx.lifecycle:lifecycle-process:2.0.0-alpha1
     |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0-alpha1 (*)
     +--- androidx.lifecycle:lifecycle-service:2.0.0-alpha1
     |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0-alpha1 (*)
     \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0-alpha1 (*)
`

I don't know where else to report this.

**Comment by keyboardsurfer** [comment]
The [Android Public Tracker](https://issuetracker.google.com/issues/new?component=316045&template=1018787) is the right place for this issue.

Please file a report and feel free to link it here.

**Comment by keyboardsurfer** [comment]
If you got around to filing an issue, please report the bug id in here for reference.

**Comment by MarkOSullivan94** [comment]
Just came across this same issue and it looks like it's on the Android Public Tracker - https://issuetracker.google.com/issues/79671572
