### ISSUE TITLE
How to read info passed in postInstall Intent

### ISSUE THREAD

**Issue by AnupamSingh0211** [googlesamples/android-instant-apps#54]
private val postInstallIntent = Intent(Intent.ACTION_VIEW,
            Uri.parse("https://install-api.instantappsample.com/")).
            addCategory(Intent.CATEGORY_BROWSABLE).
            putExtras(Bundle().apply {
                putString("The key to", "sending data via intent")
            })

Where to catch value of "the key to" In the installed app

**Comment by miguelmontemayor** [comment]
You can access the extra data from the post-install intent launched in your installed app.
```
Intent launchIntent = getIntent();
if ( launchIntent != null ) {
   userToken = launchIntent.getStringExtra(USER_PARAM);
}
```
