### ISSUE TITLE
Instant app on Android Wear

### ISSUE THREAD

**Issue by alexgtn** [googlesamples/android-instant-apps#7]
Hello, everyone!

Is it possible to open an instant app on an Android Wear device? Or to develop an instant app that could be specifically opened only on an Android Wear ex. watch?

sorry, I'm not opening an actual issue, but I don't know where to ask :)
Thank you!

**Comment by adamkoch** [comment]
Please post questions like this on stackoverflow under the instant apps tag:
https://stackoverflow.com/questions/tagged/android-instant-apps

The the answer is, no, it's not possible to run Instant Apps on Wear devices at this time.
