### ISSUE TITLE
Project failed to parse error

### ISSUE THREAD

**Issue by michealdanne** [googlesamples/android-instant-apps#8]
Hi,

I'm trying to run my instant app module but I've got the error **DevMan error: Failed to parse app: /data/local/tmp/aia/...**

However, when I run the command adb install -r -t my-base-debug.apk it gives success.

**Comment by keyboardsurfer** [comment]
Thanks for reporting this.
Could you please be more specific on how you try to run the instant app.
Through Android Studio? Installing it via adb?

Also, which of the samples do you run into issues with?

**Comment by keyboardsurfer** [comment]
Closing this issue as stale. Feel free to comment and re-open if the issue persists.
